### ISSUE TITLE
No such file

### ISSUE THREAD

**Issue by G-986** [CapnDev-Git/Minix2-iAPX86-Interpreter#1]
./include/main.h:4:10: fatal error: err.h: No such file or directory
    4 | #include <err.h>

**Comment by EliottFlechtner** [comment]
Compiles fine with `make` on a Linux environment with correct dependencies i.e `make` installation and default C header files. I suggest checking you have the default `libc` installed :) Just a reminder, this is a school project for 16b-x86 processors not used anymore today.
